#!/usr/bin/env node
import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { basename, extname, join } from 'node:path';
import {
  PI_PROVIDER_DISCOVERY_PATH,
  PI_PROVIDER_HEALTH_PATH,
  PI_PROVIDER_PROFILE_PATH,
  PI_PROVIDER_RUNS_PATH,
  ProviderConversationSchema,
  ProviderConversationSendResponseSchema,
  ProviderConversationStopResponseSchema,
  ProviderErrorEnvelopeSchema,
  ProviderHealthSchema,
  ProviderProfileSchema,
  ProviderRunSchema,
  ProviderSessionEventSchema,
  ProviderSessionEventsResponseSchema,
  ProviderSessionListResponseSchema,
  ProviderSessionMessageSchema,
  ProviderSessionMessagesResponseSchema,
  ProviderSessionReplayCompleteEventSchema,
  ProviderSessionSchema,
  createProviderConversation,
  createProviderConversationSendResponse,
  createProviderConversationStopResponse,
  createProviderErrorEnvelope,
  createProviderHealth,
  createProviderProfile,
  createProviderRun,
  createProviderSession,
  createProviderSessionEvent,
  createProviderSessionEventsResponse,
  createProviderSessionListResponse,
  createProviderSessionMessage,
  createProviderSessionMessagesResponse,
  createProviderSessionReplayCompleteEvent,
  getSchemaErrors,
  providerConversationMessagesPath,
  providerConversationPath,
  providerConversationStopPath,
  providerRunCancelPath,
  providerRunPath,
  providerSessionEventsPath,
  providerSessionEventsStreamPath,
  providerSessionMessagesPath,
  providerSessionPath,
  type ProviderConversation,
  type ProviderConversationSendResponse,
  type ProviderConversationStopResponse,
  type ProviderErrorEnvelope,
  type ProviderHealth,
  type ProviderProfile,
  type ProviderRun,
  type ProviderSession,
  type ProviderSessionEvent,
  type ProviderSessionEventsResponse,
  type ProviderSessionListResponse,
  type ProviderSessionMessage,
  type ProviderSessionMessagesResponse,
  type ProviderSessionReplayCompleteEvent,
} from './index.js';
import type { TSchema } from '@sinclair/typebox';
import { Value } from '@sinclair/typebox/value';

type ValidationCheck = {
  file: string;
  ok: boolean;
  schema: string | null;
  errors: string[];
};

type NamedSchema = {
  name: string;
  schema: TSchema;
};

type InspectCheck = {
  name: string;
  method: string;
  path: string;
  ok: boolean;
  status: number | null;
  schema: string | null;
  errors: string[];
  skipped?: boolean;
};

type InspectOptions = {
  baseUrl: string;
  json: boolean;
  createRun: boolean;
  token: string | null;
  input: string;
};

const SCHEMAS: NamedSchema[] = [
  { name: 'ProviderProfile', schema: ProviderProfileSchema },
  { name: 'ProviderHealth', schema: ProviderHealthSchema },
  { name: 'ProviderErrorEnvelope', schema: ProviderErrorEnvelopeSchema },
  { name: 'ProviderRun', schema: ProviderRunSchema },
  { name: 'ProviderSession', schema: ProviderSessionSchema },
  { name: 'ProviderSessionListResponse', schema: ProviderSessionListResponseSchema },
  { name: 'ProviderSessionMessage', schema: ProviderSessionMessageSchema },
  { name: 'ProviderSessionMessagesResponse', schema: ProviderSessionMessagesResponseSchema },
  { name: 'ProviderSessionEvent', schema: ProviderSessionEventSchema },
  { name: 'ProviderSessionEventsResponse', schema: ProviderSessionEventsResponseSchema },
  { name: 'ProviderSessionReplayCompleteEvent', schema: ProviderSessionReplayCompleteEventSchema },
  { name: 'ProviderConversation', schema: ProviderConversationSchema },
  { name: 'ProviderConversationSendResponse', schema: ProviderConversationSendResponseSchema },
  { name: 'ProviderConversationStopResponse', schema: ProviderConversationStopResponseSchema },
];

const FIXTURES = new Map<string, unknown>([
  [
    'provider-profile.json',
    createProviderProfile({
      profile: {
        id: 'example-agent',
        displayName: 'Example Agent',
        headline: 'Protocol-compliant example provider',
        summary: 'Example provider profile generated by pi-protocol.',
        links: [],
      },
      skills: [{ name: 'example-skill', description: 'Demonstrates provider profile skills.' }],
    }) satisfies ProviderProfile,
  ],
  [
    'health.json',
    createProviderHealth({
      service: 'example-pi-os-provider',
      version: '0.0.0',
      status: { readiness: 'ready', activeRuns: 0, queuedRuns: 0, maxConcurrentRuns: 1 },
    }) satisfies ProviderHealth,
  ],
  [
    'error-envelope.json',
    createProviderErrorEnvelope({
      code: 'provider.unavailable',
      message: 'Provider is temporarily unavailable',
      retryable: true,
    }) satisfies ProviderErrorEnvelope,
  ],
  [
    'run.json',
    createProviderRun({
      id: 'run_example',
      status: 'queued',
      sessionId: 'session_example',
      createdAt: '2026-05-25T00:00:00.000Z',
    }) satisfies ProviderRun,
  ],
  [
    'session.json',
    createProviderSession({
      id: 'session_example',
      runId: 'run_example',
      status: 'running',
      activity: 'active',
      lastEventSeq: 1,
      createdAt: '2026-05-25T00:00:00.000Z',
      updatedAt: '2026-05-25T00:00:01.000Z',
    }) satisfies ProviderSession,
  ],
  [
    'sessions.json',
    createProviderSessionListResponse({ sessions: [] }) satisfies ProviderSessionListResponse,
  ],
  [
    'message.json',
    createProviderSessionMessage({
      id: 'message_example',
      sessionId: 'session_example',
      role: 'assistant',
      content: 'Example assistant message.',
      createdAt: '2026-05-25T00:00:01.000Z',
    }) satisfies ProviderSessionMessage,
  ],
  [
    'messages.json',
    createProviderSessionMessagesResponse({ messages: [] }) satisfies ProviderSessionMessagesResponse,
  ],
  [
    'event.json',
    createProviderSessionEvent({
      seq: 1,
      sessionId: 'session_example',
      type: 'message.created',
      payload: { messageId: 'message_example' },
      createdAt: '2026-05-25T00:00:01.000Z',
    }) satisfies ProviderSessionEvent,
  ],
  [
    'events.json',
    createProviderSessionEventsResponse({ events: [] }) satisfies ProviderSessionEventsResponse,
  ],
  [
    'replay-complete-event.json',
    createProviderSessionReplayCompleteEvent({
      seq: 2,
      sessionId: 'session_example',
      type: 'session.replay_complete',
      createdAt: '2026-05-25T00:00:02.000Z',
    }) satisfies ProviderSessionReplayCompleteEvent,
  ],
  [
    'conversation.json',
    createProviderConversation({
      sessionId: 'session_example',
      status: 'idle',
      messages: [],
      lastEventSeq: 2,
    }) satisfies ProviderConversation,
  ],
  [
    'conversation-send-response.json',
    createProviderConversationSendResponse({
      accepted: true,
      sessionId: 'session_example',
      messageId: 'message_user_example',
      turnId: 'turn_example',
      status: 'queued',
    }) satisfies ProviderConversationSendResponse,
  ],
  [
    'conversation-stop-response.json',
    createProviderConversationStopResponse({
      stoppedCurrent: true,
      cancelledQueued: 0,
    }) satisfies ProviderConversationStopResponse,
  ],
]);

function printUsage(): void {
  console.log(`pi-protocol CLI

Usage:
  pi-protocol init-provider [directory]
  pi-protocol validate <path> [--json]
  pi-protocol inspect-provider <baseUrl> [--json] [--token <token>] [--create-run] [--input <text>]
  pi-protocol help

Commands:
  init-provider   Generate framework-neutral provider fixtures and a README.
  validate        Validate JSON fixtures against known pi-protocol schemas.
  inspect-provider Check a live provider's mandatory interface surface.
`);
}

async function main(argv: string[]): Promise<number> {
  const [command, ...args] = argv;
  if (!command || command === 'help' || command === '--help' || command === '-h') {
    printUsage();
    return 0;
  }

  if (command === 'init-provider') {
    return initProvider(args[0] ?? 'pi-provider-fixtures');
  }

  if (command === 'validate') {
    const target = args.find((arg) => !arg.startsWith('-'));
    if (!target) {
      console.error('Missing path: pi-protocol validate <path>');
      return 2;
    }
    return validateTarget(target, args.includes('--json'));
  }

  if (command === 'inspect-provider') {
    return inspectProvider(parseInspectOptions(args));
  }

  console.error(`Unknown command: ${command}`);
  printUsage();
  return 2;
}

function initProvider(directory: string): number {
  mkdirSync(directory, { recursive: true });
  for (const [file, value] of FIXTURES) {
    writeJson(join(directory, file), value);
  }
  writeFileSync(
    join(directory, 'README.md'),
    `# pi-protocol provider fixtures\n\nThese framework-neutral fixtures were generated by \`pi-protocol init-provider\`.\n\nValidate them with:\n\n\`\`\`bash\npi-protocol validate ${directory}\n\`\`\`\n\nUse these JSON shapes as contract examples when implementing a pi-os provider.\n`,
    'utf8',
  );
  console.log(`Generated pi-protocol provider fixtures in ${directory}`);
  return 0;
}

function validateTarget(target: string, json: boolean): number {
  const files = collectJsonFiles(target);
  const checks = files.map(validateFile);
  const failed = checks.filter((check) => !check.ok);

  if (json) {
    console.log(JSON.stringify({ ok: failed.length === 0, checks }, null, 2));
  } else {
    for (const check of checks) {
      if (check.ok) {
        console.log(`✓ ${check.file} (${check.schema})`);
      } else {
        console.log(`✗ ${check.file}`);
        for (const error of check.errors) {
          console.log(`  - ${error}`);
        }
      }
    }
    console.log(failed.length === 0 ? `Validated ${checks.length} file(s)` : `Failed ${failed.length}/${checks.length} file(s)`);
  }

  return failed.length === 0 ? 0 : 1;
}

function collectJsonFiles(target: string): string[] {
  const stat = statSync(target);
  if (stat.isFile()) {
    return [target];
  }
  if (!stat.isDirectory()) {
    throw new Error(`Not a file or directory: ${target}`);
  }
  return readdirSync(target)
    .map((entry) => join(target, entry))
    .filter((path) => statSync(path).isFile() && extname(path) === '.json')
    .sort();
}

function validateFile(file: string): ValidationCheck {
  const value = JSON.parse(readFileSync(file, 'utf8')) as unknown;
  const candidates = preferredSchemasForFile(file);
  for (const candidate of candidates) {
    if (Value.Check(candidate.schema, value)) {
      return { file, ok: true, schema: candidate.name, errors: [] };
    }
  }

  const fallback = candidates[0] ?? SCHEMAS[0];
  return {
    file,
    ok: false,
    schema: null,
    errors: fallback ? getSchemaErrors(fallback.schema, value) : ['no schemas available'],
  };
}

function preferredSchemasForFile(file: string): NamedSchema[] {
  const lower = basename(file).toLowerCase();
  const scored = SCHEMAS.map((schema) => ({ schema, score: schemaScore(lower, schema.name.toLowerCase()) }))
    .filter((entry) => entry.score > 0)
    .sort((a, b) => b.score - a.score)
    .map((entry) => entry.schema);
  return scored.length > 0 ? scored : SCHEMAS;
}

function schemaScore(file: string, schema: string): number {
  if (file.includes('profile') && schema.includes('profile')) return 100;
  if (file.includes('health') && schema.includes('health')) return 100;
  if (file.includes('error') && schema.includes('error')) return 100;
  if (file.includes('replay') && schema.includes('replay')) return 100;
  if (file.includes('send') && schema.includes('sendresponse')) return 100;
  if (file.includes('stop') && schema.includes('stopresponse')) return 100;
  if (file.includes('conversation') && schema === 'providerconversation') return 90;
  if (file.includes('sessions') && schema.includes('sessionlist')) return 100;
  if (file.includes('session') && schema === 'providersession') return 90;
  if (file.includes('messages') && schema.includes('messagesresponse')) return 100;
  if (file.includes('message') && schema === 'providersessionmessage') return 90;
  if (file.includes('events') && schema.includes('eventsresponse')) return 100;
  if (file.includes('event') && schema === 'providersessionevent') return 90;
  if (file.includes('run') && schema === 'providerrun') return 90;
  return 0;
}

function writeJson(path: string, value: unknown): void {
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

function parseInspectOptions(args: string[]): InspectOptions {
  const baseUrl = args.find((arg) => !arg.startsWith('-'));
  if (!baseUrl) {
    throw new Error('Missing baseUrl: pi-protocol inspect-provider <baseUrl>');
  }

  return {
    baseUrl,
    json: args.includes('--json'),
    createRun: args.includes('--create-run'),
    token: readOption(args, '--token') ?? process.env.PI_PROVIDER_TOKEN ?? null,
    input: readOption(args, '--input') ?? 'pi-protocol full contract smoke test',
  };
}

function readOption(args: string[], flag: string): string | null {
  const index = args.indexOf(flag);
  if (index === -1) return null;
  return args[index + 1] ?? null;
}

async function inspectProvider(options: InspectOptions): Promise<number> {
  const checks: InspectCheck[] = [];
  const authHeaders: Record<string, string> = options.token ? { Authorization: `Bearer ${options.token}` } : {};
  let runId: string | null = null;
  let sessionId: string | null = null;

  await checkJson(checks, options, 'discovery', 'GET', PI_PROVIDER_DISCOVERY_PATH, ProviderProfileSchema, 'ProviderProfile', authHeaders);
  await checkJson(checks, options, 'profile', 'GET', PI_PROVIDER_PROFILE_PATH, ProviderProfileSchema, 'ProviderProfile', authHeaders);
  await checkJson(checks, options, 'health', 'GET', PI_PROVIDER_HEALTH_PATH, ProviderHealthSchema, 'ProviderHealth', authHeaders);

  if (!options.createRun) {
    addSkipped(checks, 'create run', 'POST', PI_PROVIDER_RUNS_PATH, 'pass --create-run to run side-effect checks');
  } else {
    const created = await checkJson(
      checks,
      options,
      'create run',
      'POST',
      PI_PROVIDER_RUNS_PATH,
      ProviderRunSchema,
      'ProviderRun',
      { ...authHeaders, 'Content-Type': 'application/json' },
      { input: options.input, context: { source: 'pi-protocol.inspect-provider' } },
    );
    if (created.ok && typeof created.value === 'object' && created.value !== null) {
      const run = created.value as { id?: unknown; sessionId?: unknown };
      runId = typeof run.id === 'string' ? run.id : null;
      sessionId = typeof run.sessionId === 'string' ? run.sessionId : null;
    }

    if (runId) {
      await checkJson(checks, options, 'read run', 'GET', providerRunPath(runId), ProviderRunSchema, 'ProviderRun', authHeaders);
      await checkJson(checks, options, 'cancel run', 'POST', providerRunCancelPath(runId), ProviderRunSchema, 'ProviderRun', authHeaders);
    } else {
      addSkipped(checks, 'read run', 'GET', '/runs/:runId', 'create run did not return run id');
      addSkipped(checks, 'cancel run', 'POST', '/runs/:runId/cancel', 'create run did not return run id');
    }

    await checkJson(checks, options, 'list sessions', 'GET', '/sessions', ProviderSessionListResponseSchema, 'ProviderSessionListResponse', authHeaders);

    if (sessionId) {
      await checkJson(checks, options, 'read session', 'GET', providerSessionPath(sessionId), ProviderSessionSchema, 'ProviderSession', authHeaders);
      await checkJson(checks, options, 'session messages', 'GET', providerSessionMessagesPath(sessionId), ProviderSessionMessagesResponseSchema, 'ProviderSessionMessagesResponse', authHeaders);
      await checkJson(checks, options, 'session events', 'GET', providerSessionEventsPath(sessionId), ProviderSessionEventsResponseSchema, 'ProviderSessionEventsResponse', authHeaders);
      await checkJson(checks, options, 'read conversation', 'GET', providerConversationPath(sessionId), ProviderConversationSchema, 'ProviderConversation', authHeaders);
      await checkJson(
        checks,
        options,
        'send conversation message',
        'POST',
        providerConversationMessagesPath(sessionId),
        ProviderConversationSendResponseSchema,
        'ProviderConversationSendResponse',
        { ...authHeaders, 'Content-Type': 'application/json' },
        { content: options.input },
      );
      await checkJson(checks, options, 'stop conversation', 'POST', providerConversationStopPath(sessionId), ProviderConversationStopResponseSchema, 'ProviderConversationStopResponse', authHeaders);
      await checkSse(checks, options, 'session event stream', providerSessionEventsStreamPath(sessionId), authHeaders);
    } else {
      for (const [name, method, path] of [
        ['read session', 'GET', '/sessions/:sessionId'],
        ['session messages', 'GET', '/sessions/:sessionId/messages'],
        ['session events', 'GET', '/sessions/:sessionId/events'],
        ['read conversation', 'GET', '/conversations/:sessionId'],
        ['send conversation message', 'POST', '/conversations/:sessionId/messages'],
        ['stop conversation', 'POST', '/conversations/:sessionId/stop'],
        ['session event stream', 'GET', '/sessions/:sessionId/events/stream'],
      ] as const) {
        addSkipped(checks, name, method, path, 'create run did not return session id');
      }
    }
  }

  const failed = checks.filter((check) => !check.ok && !check.skipped);
  if (options.json) {
    console.log(JSON.stringify({ ok: failed.length === 0, checks }, null, 2));
  } else {
    for (const check of checks) {
      const mark = check.skipped ? '-' : check.ok ? '✓' : '✗';
      console.log(`${mark} ${check.method} ${check.path} ${check.name}${check.status ? ` (${check.status})` : ''}`);
      for (const error of check.errors) console.log(`  - ${error}`);
    }
    console.log(failed.length === 0 ? `Provider contract checks passed (${checks.length} checks)` : `Provider contract checks failed (${failed.length}/${checks.length})`);
  }
  return failed.length === 0 ? 0 : 1;
}

async function checkJson(
  checks: InspectCheck[],
  options: InspectOptions,
  name: string,
  method: string,
  path: string,
  schema: TSchema,
  schemaName: string,
  headers: Record<string, string>,
  body?: unknown,
): Promise<{ ok: boolean; value: unknown }> {
  try {
    const response = await fetch(new URL(path, options.baseUrl), {
      method,
      headers,
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    const value = await response.json() as unknown;
    const schemaOk = Value.Check(schema, value);
    checks.push({
      name,
      method,
      path,
      ok: response.ok && schemaOk,
      status: response.status,
      schema: schemaName,
      errors: response.ok ? (schemaOk ? [] : getSchemaErrors(schema, value)) : [`HTTP ${response.status}`],
    });
    return { ok: response.ok && schemaOk, value };
  } catch (error) {
    checks.push({ name, method, path, ok: false, status: null, schema: schemaName, errors: [redact(String(error), options.token)] });
    return { ok: false, value: null };
  }
}

async function checkSse(
  checks: InspectCheck[],
  options: InspectOptions,
  name: string,
  path: string,
  headers: Record<string, string>,
): Promise<void> {
  try {
    const response = await fetch(new URL(path, options.baseUrl), { method: 'GET', headers: { ...headers, Accept: 'text/event-stream' } });
    const contentType = response.headers.get('content-type') ?? '';
    const ok = response.ok && contentType.includes('text/event-stream');
    await response.body?.cancel();
    checks.push({ name, method: 'GET', path, ok, status: response.status, schema: 'text/event-stream', errors: ok ? [] : [`expected text/event-stream, got ${contentType || 'unknown'}`] });
  } catch (error) {
    checks.push({ name, method: 'GET', path, ok: false, status: null, schema: 'text/event-stream', errors: [redact(String(error), options.token)] });
  }
}

function addSkipped(checks: InspectCheck[], name: string, method: string, path: string, reason: string): void {
  checks.push({ name, method, path, ok: true, status: null, schema: null, errors: [reason], skipped: true });
}

function redact(value: string, token: string | null): string {
  return token ? value.split(token).join('[REDACTED]') : value;
}

try {
  process.exitCode = await main(process.argv.slice(2));
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
}
