#!/usr/bin/env node
import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { basename, extname, join } from 'node:path';
import {
  ProviderConversationSchema,
  ProviderConversationSendResponseSchema,
  ProviderConversationStopResponseSchema,
  ProviderErrorEnvelopeSchema,
  ProviderHealthSchema,
  ProviderProfileSchema,
  ProviderRunSchema,
  ProviderSessionEventSchema,
  ProviderSessionEventsResponseSchema,
  ProviderSessionListResponseSchema,
  ProviderSessionMessageSchema,
  ProviderSessionMessagesResponseSchema,
  ProviderSessionReplayCompleteEventSchema,
  ProviderSessionSchema,
  createProviderConversation,
  createProviderConversationSendResponse,
  createProviderConversationStopResponse,
  createProviderErrorEnvelope,
  createProviderHealth,
  createProviderProfile,
  createProviderRun,
  createProviderSession,
  createProviderSessionEvent,
  createProviderSessionEventsResponse,
  createProviderSessionListResponse,
  createProviderSessionMessage,
  createProviderSessionMessagesResponse,
  createProviderSessionReplayCompleteEvent,
  getSchemaErrors,
  type ProviderConversation,
  type ProviderConversationSendResponse,
  type ProviderConversationStopResponse,
  type ProviderErrorEnvelope,
  type ProviderHealth,
  type ProviderProfile,
  type ProviderRun,
  type ProviderSession,
  type ProviderSessionEvent,
  type ProviderSessionEventsResponse,
  type ProviderSessionListResponse,
  type ProviderSessionMessage,
  type ProviderSessionMessagesResponse,
  type ProviderSessionReplayCompleteEvent,
} from './index.js';
import type { TSchema } from '@sinclair/typebox';
import { Value } from '@sinclair/typebox/value';

type ValidationCheck = {
  file: string;
  ok: boolean;
  schema: string | null;
  errors: string[];
};

type NamedSchema = {
  name: string;
  schema: TSchema;
};

const SCHEMAS: NamedSchema[] = [
  { name: 'ProviderProfile', schema: ProviderProfileSchema },
  { name: 'ProviderHealth', schema: ProviderHealthSchema },
  { name: 'ProviderErrorEnvelope', schema: ProviderErrorEnvelopeSchema },
  { name: 'ProviderRun', schema: ProviderRunSchema },
  { name: 'ProviderSession', schema: ProviderSessionSchema },
  { name: 'ProviderSessionListResponse', schema: ProviderSessionListResponseSchema },
  { name: 'ProviderSessionMessage', schema: ProviderSessionMessageSchema },
  { name: 'ProviderSessionMessagesResponse', schema: ProviderSessionMessagesResponseSchema },
  { name: 'ProviderSessionEvent', schema: ProviderSessionEventSchema },
  { name: 'ProviderSessionEventsResponse', schema: ProviderSessionEventsResponseSchema },
  { name: 'ProviderSessionReplayCompleteEvent', schema: ProviderSessionReplayCompleteEventSchema },
  { name: 'ProviderConversation', schema: ProviderConversationSchema },
  { name: 'ProviderConversationSendResponse', schema: ProviderConversationSendResponseSchema },
  { name: 'ProviderConversationStopResponse', schema: ProviderConversationStopResponseSchema },
];

const FIXTURES = new Map<string, unknown>([
  [
    'provider-profile.json',
    createProviderProfile({
      profile: {
        id: 'example-agent',
        displayName: 'Example Agent',
        headline: 'Protocol-compliant example provider',
        summary: 'Example provider profile generated by pi-protocol.',
        links: [],
      },
      skills: [{ name: 'example-skill', description: 'Demonstrates provider profile skills.' }],
    }) satisfies ProviderProfile,
  ],
  [
    'health.json',
    createProviderHealth({
      service: 'example-pi-os-provider',
      version: '0.0.0',
      status: { readiness: 'ready', activeRuns: 0, queuedRuns: 0, maxConcurrentRuns: 1 },
    }) satisfies ProviderHealth,
  ],
  [
    'error-envelope.json',
    createProviderErrorEnvelope({
      code: 'provider.unavailable',
      message: 'Provider is temporarily unavailable',
      retryable: true,
    }) satisfies ProviderErrorEnvelope,
  ],
  [
    'run.json',
    createProviderRun({
      id: 'run_example',
      status: 'queued',
      sessionId: 'session_example',
      createdAt: '2026-05-25T00:00:00.000Z',
    }) satisfies ProviderRun,
  ],
  [
    'session.json',
    createProviderSession({
      id: 'session_example',
      runId: 'run_example',
      status: 'running',
      activity: 'active',
      lastEventSeq: 1,
      createdAt: '2026-05-25T00:00:00.000Z',
      updatedAt: '2026-05-25T00:00:01.000Z',
    }) satisfies ProviderSession,
  ],
  [
    'sessions.json',
    createProviderSessionListResponse({ sessions: [] }) satisfies ProviderSessionListResponse,
  ],
  [
    'message.json',
    createProviderSessionMessage({
      id: 'message_example',
      sessionId: 'session_example',
      role: 'assistant',
      content: 'Example assistant message.',
      createdAt: '2026-05-25T00:00:01.000Z',
    }) satisfies ProviderSessionMessage,
  ],
  [
    'messages.json',
    createProviderSessionMessagesResponse({ messages: [] }) satisfies ProviderSessionMessagesResponse,
  ],
  [
    'event.json',
    createProviderSessionEvent({
      seq: 1,
      sessionId: 'session_example',
      type: 'message.created',
      payload: { messageId: 'message_example' },
      createdAt: '2026-05-25T00:00:01.000Z',
    }) satisfies ProviderSessionEvent,
  ],
  [
    'events.json',
    createProviderSessionEventsResponse({ events: [] }) satisfies ProviderSessionEventsResponse,
  ],
  [
    'replay-complete-event.json',
    createProviderSessionReplayCompleteEvent({
      seq: 2,
      sessionId: 'session_example',
      type: 'session.replay_complete',
      createdAt: '2026-05-25T00:00:02.000Z',
    }) satisfies ProviderSessionReplayCompleteEvent,
  ],
  [
    'conversation.json',
    createProviderConversation({
      sessionId: 'session_example',
      status: 'idle',
      messages: [],
      lastEventSeq: 2,
    }) satisfies ProviderConversation,
  ],
  [
    'conversation-send-response.json',
    createProviderConversationSendResponse({
      accepted: true,
      sessionId: 'session_example',
      messageId: 'message_user_example',
      turnId: 'turn_example',
      status: 'queued',
    }) satisfies ProviderConversationSendResponse,
  ],
  [
    'conversation-stop-response.json',
    createProviderConversationStopResponse({
      stoppedCurrent: true,
      cancelledQueued: 0,
    }) satisfies ProviderConversationStopResponse,
  ],
]);

function printUsage(): void {
  console.log(`pi-protocol CLI

Usage:
  pi-protocol init-provider [directory]
  pi-protocol validate <path> [--json]
  pi-protocol help

Commands:
  init-provider   Generate framework-neutral provider fixtures and a README.
  validate        Validate JSON fixtures against known pi-protocol schemas.
`);
}

function main(argv: string[]): number {
  const [command, ...args] = argv;
  if (!command || command === 'help' || command === '--help' || command === '-h') {
    printUsage();
    return 0;
  }

  if (command === 'init-provider') {
    return initProvider(args[0] ?? 'pi-provider-fixtures');
  }

  if (command === 'validate') {
    const target = args.find((arg) => !arg.startsWith('-'));
    if (!target) {
      console.error('Missing path: pi-protocol validate <path>');
      return 2;
    }
    return validateTarget(target, args.includes('--json'));
  }

  console.error(`Unknown command: ${command}`);
  printUsage();
  return 2;
}

function initProvider(directory: string): number {
  mkdirSync(directory, { recursive: true });
  for (const [file, value] of FIXTURES) {
    writeJson(join(directory, file), value);
  }
  writeFileSync(
    join(directory, 'README.md'),
    `# pi-protocol provider fixtures\n\nThese framework-neutral fixtures were generated by \`pi-protocol init-provider\`.\n\nValidate them with:\n\n\`\`\`bash\npi-protocol validate ${directory}\n\`\`\`\n\nUse these JSON shapes as contract examples when implementing a pi-os provider.\n`,
    'utf8',
  );
  console.log(`Generated pi-protocol provider fixtures in ${directory}`);
  return 0;
}

function validateTarget(target: string, json: boolean): number {
  const files = collectJsonFiles(target);
  const checks = files.map(validateFile);
  const failed = checks.filter((check) => !check.ok);

  if (json) {
    console.log(JSON.stringify({ ok: failed.length === 0, checks }, null, 2));
  } else {
    for (const check of checks) {
      if (check.ok) {
        console.log(`✓ ${check.file} (${check.schema})`);
      } else {
        console.log(`✗ ${check.file}`);
        for (const error of check.errors) {
          console.log(`  - ${error}`);
        }
      }
    }
    console.log(failed.length === 0 ? `Validated ${checks.length} file(s)` : `Failed ${failed.length}/${checks.length} file(s)`);
  }

  return failed.length === 0 ? 0 : 1;
}

function collectJsonFiles(target: string): string[] {
  const stat = statSync(target);
  if (stat.isFile()) {
    return [target];
  }
  if (!stat.isDirectory()) {
    throw new Error(`Not a file or directory: ${target}`);
  }
  return readdirSync(target)
    .map((entry) => join(target, entry))
    .filter((path) => statSync(path).isFile() && extname(path) === '.json')
    .sort();
}

function validateFile(file: string): ValidationCheck {
  const value = JSON.parse(readFileSync(file, 'utf8')) as unknown;
  const candidates = preferredSchemasForFile(file);
  for (const candidate of candidates) {
    if (Value.Check(candidate.schema, value)) {
      return { file, ok: true, schema: candidate.name, errors: [] };
    }
  }

  const fallback = candidates[0] ?? SCHEMAS[0];
  return {
    file,
    ok: false,
    schema: null,
    errors: fallback ? getSchemaErrors(fallback.schema, value) : ['no schemas available'],
  };
}

function preferredSchemasForFile(file: string): NamedSchema[] {
  const lower = basename(file).toLowerCase();
  const scored = SCHEMAS.map((schema) => ({ schema, score: schemaScore(lower, schema.name.toLowerCase()) }))
    .filter((entry) => entry.score > 0)
    .sort((a, b) => b.score - a.score)
    .map((entry) => entry.schema);
  return scored.length > 0 ? scored : SCHEMAS;
}

function schemaScore(file: string, schema: string): number {
  if (file.includes('profile') && schema.includes('profile')) return 100;
  if (file.includes('health') && schema.includes('health')) return 100;
  if (file.includes('error') && schema.includes('error')) return 100;
  if (file.includes('replay') && schema.includes('replay')) return 100;
  if (file.includes('send') && schema.includes('sendresponse')) return 100;
  if (file.includes('stop') && schema.includes('stopresponse')) return 100;
  if (file.includes('conversation') && schema === 'providerconversation') return 90;
  if (file.includes('sessions') && schema.includes('sessionlist')) return 100;
  if (file.includes('session') && schema === 'providersession') return 90;
  if (file.includes('messages') && schema.includes('messagesresponse')) return 100;
  if (file.includes('message') && schema === 'providersessionmessage') return 90;
  if (file.includes('events') && schema.includes('eventsresponse')) return 100;
  if (file.includes('event') && schema === 'providersessionevent') return 90;
  if (file.includes('run') && schema === 'providerrun') return 90;
  return 0;
}

function writeJson(path: string, value: unknown): void {
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

try {
  process.exitCode = main(process.argv.slice(2));
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
}
